export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED", // 401
  VALIDATION_FAILED: "VALIDATION_FAILED", // 400
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_ERROR", // 500
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
